### ISSUE TITLE
Register profile error

### ISSUE THREAD

**Issue by eeggssyy** [Baylor-SEII-Projects-Spring-2024/study-buddy-finder-group-1#111]
Same error as edit profile when creating a new account

**Comment by nickrevard9** [comment]
In User     @JsonManagedReference is causing an issue with the payload and is not accepting it as a valid media type
I am currently looking into it.

**Comment by eeggssyy** [comment]
> In User @JsonManagedReference is causing an issue with the payload and is not accepting it as a valid media type I am currently looking into it.

We'll see if we can work without having that. I have it commented out for the time being to fix other issues and I haven't noticed any problems so far
