### ISSUE TITLE
Search tutor subject

### ISSUE THREAD

**Issue by eeggssyy** [Baylor-SEII-Projects-Spring-2024/study-buddy-finder-group-1#121]
When searching for a tutor the subject they teach is hitting the default case of show the search term because it cant find a matching subject

**Comment by nickrevard9** [comment]
I am gonna take a look at this.

**Comment by nickrevard9** [comment]
This has been fixed also this will stop showing multiples of the tutor if they had multiple courses fitting the searchterm will be uploaded soon
