### ISSUE TITLE
User not logged in

### ISSUE THREAD

**Issue by eeggssyy** [Baylor-SEII-Projects-Spring-2024/study-buddy-finder-group-1#72]
When not logged in, all links are still shown. The website should only give the user an option to log in or make an account

**Comment by KyleThompson1** [comment]
I'll take care of this.

**Comment by VinnyD-Code** [comment]
linked seem to be removed, can you guys confirm

**Comment by eeggssyy** [comment]
@VinnyD-Code ill confirm and close if good later tonight and work on it if not

**Comment by eeggssyy** [comment]
> linked seem to be removed, can you guys confirm

I believe the issues comes from relaunching the site on the same browser and your account stays logged in. I launched the site on edge after encountering the issue again and it did not happen on edge. I didn't test the buttons on chrome (where the issue occurred) to make sure they work so Im not completely sure this was the issue yet

**Comment by KyleThompson1** [comment]
I changed the home page to only allow a user to sign in or register. Ill work on logging out a user after x amount of time has passed. Maybe that will fix it.
